Import GnuTLS v3.3.22

diff --git a/tests/cert-tests/template-test b/tests/cert-tests/template-test
--- a/tests/cert-tests/template-test
+++ b/tests/cert-tests/template-test
@@ -23,9 +23,12 @@
 srcdir=${srcdir:-.}
 CERTTOOL=${CERTTOOL:-../../src/certtool$EXEEXT}
 
+export TZ="UTC"
+
 # Check for datefudge
 TSTAMP=`datefudge "2006-09-23" date -u +%s || true`
-if test "$TSTAMP" != "1158962400"; then
+if test "$TSTAMP" != "1158969600"; then
+echo $TSTAMP
     echo "You need datefudge to run this test"
     exit 77
 fi
@@ -121,6 +124,9 @@ fi
 
 rm -f tmp-tt.pem
 
+# The following test works in 64-bit systems
+if echo __SIZEOF_POINTER__ | cpp -E - - | grep '^8$' >/dev/null; then
+
 rc=1
 counter=1
 
@@ -144,6 +150,7 @@ if test "$rc" != "0"; then
 fi
 
 rm -f tmp-tt.pem
+fi
 
 rc=1
 counter=1
@@ -214,6 +221,33 @@ done
 # We're done.
 if test "$rc" != "0"; then
   echo "Test 7 (name constraints) failed"
+  exit $rc
+fi
+
+rm -f tmp-tt.pem
+
+# Test the GeneralizedTime support
+rc=1
+counter=1
+
+while [ "$rc" != "0" -a $counter -le 3 ]
+do
+      
+datefudge "2051-04-22" \
+    $CERTTOOL --generate-self-signed \
+    --load-privkey $srcdir/template-test.key \
+    --template $srcdir/template-generalized.tmpl \
+    --outfile tmp-tt.pem 2>/dev/null
+
+diff $srcdir/template-generalized.pem tmp-tt.pem >/dev/null 2>&1
+rc=$?
+test $rc != 0 && sleep 3
+counter=`expr $counter + 1` 
+done
+
+# We're done.
+if test "$rc" != "0"; then
+  echo "Test 8 (generalizedTime) failed"
   exit $rc
 fi
 
